// Same default rows as supabase_schema.sql, used to power preview mode.
const DEPARTMENTS = ["ICU", "NICU", "الجراحة", "النساء"];

export const checklist_types = [
  {
    id: "ct-ssi",
    code: "SSI",
    name_ar: "الجراحة (SSI)",
    name_en: "Surgical Site Infection",
    active: true,
    sort_order: 1,
    departments: ["الجراحة", "النساء"],
    items: [
      "1. Antibiotic(s) was (were) given within one (1) hour before incision",
      "2. Prophylactic antibiotic(s) is (are) consistent with our guidelines",
      "3. Discontinuation of prophylactic antibiotic(s) within 24 hours",
      "4. Appropriate hair removal — Was hair at the incisional site removed appropriately",
      "5. Maintenance of pre/postoperative glucose control — Serum glucose target met",
      "6. Maintenance of pre/postoperative normothermia (for applicable procedures)",
      "7. Use appropriate antiseptic solution",
    ],
  },
  {
    id: "ct-cauti",
    code: "CAUTI",
    name_ar: "قسطرة المسالك البولية (CAUTI)",
    name_en: "Catheter-Associated UTI",
    active: true,
    sort_order: 2,
    departments: ["ICU", "الجراحة", "النساء"],
    items: [
      "1. Avoid unnecessary urinary catheters",
      "2. Insert using aseptic technique",
      "3. Hand hygiene before insertion of urinary catheter",
      "4. Use sterile equipment (gloves, drape, sponges, sterile solution)",
      "5. Use of smallest catheter size as possible",
      "6. Maintain catheters based on recommended guidelines",
      "7. Maintain a sterile, continuously closed drainage system",
      "8. Keep catheter properly secured to prevent movement",
      "9. Keep collection bag below the level of the bladder at all times",
      "10. Maintain unobstructed urine flow",
      "11. Empty collection bag regularly",
      "12. Routine hygiene (cleansing of the meatal surface)",
      "13. Collection of urine samples should follow aseptic technique",
      "14. Review urinary catheter necessity daily and remove promptly when no longer indicated",
    ],
  },
  {
    id: "ct-vae-icu",
    code: "VAE_ICU",
    name_ar: "أجهزة التنفس - ICU (VAE)",
    name_en: "Ventilator-Associated Event — ICU",
    active: true,
    sort_order: 3,
    departments: ["ICU"],
    items: [
      "1. Elevation of the head of the bed to between 30 and 45 degrees",
      "2. Daily sedative interruption & daily assessment of readiness to extubate",
      "3. Peptic ulcer disease (PUD) prophylaxis",
      "4. Deep venous thrombosis (DVT) prophylaxis (unless contraindicated)",
      "5. Daily oral care with appropriate antiseptic solution",
    ],
  },
  {
    id: "ct-vae-nicu",
    code: "VAE_NICU",
    name_ar: "أجهزة التنفس - NICU (VAE)",
    name_en: "Ventilator-Associated Event — NICU",
    active: true,
    sort_order: 4,
    departments: ["NICU"],
    items: [
      "1. Hand hygiene",
      "2. Semi-recumbent position",
      "3. Mouth rinse with an appropriate solution",
      "4. Appropriate ventilator circuit care",
      "5. Daily assessment of readiness to extubate",
    ],
  },
  {
    id: "ct-clabsi-icu",
    code: "CLABSI_ICU",
    name_ar: "القسطرة المركزية - ICU (CLABSI)",
    name_en: "Central Line-Associated Bloodstream Infection — ICU",
    active: true,
    sort_order: 5,
    departments: ["ICU"],
    items: [
      "1. Hand hygiene",
      "2. Maximal barrier precautions",
      "3. Cap",
      "4. Mask",
      "5. Sterile gloves",
      "6. Sterile gown",
      "7. Large sterile drape",
      "8. 2% chlorhexidine in alcohol for adults, pediatrics & neonates ≥2 months",
      "9. 2% aqueous chlorhexidine for neonates <2 weeks or <1500 g",
      "10. Subclavian vein for adults, femoral for pediatrics, and appropriate site for neonates",
      "11. Insertion compliance: compliant for the above (insertion bundle)",
      "12. Hand hygiene (maintenance)",
      "13. Daily assessment of catheter necessity with prompt removal",
      "14. Proper dressing choice (transparent semipermeable dressing)",
      "15. Proper frequency of dressing change",
      "16. Proper replacement of administration sets",
    ],
  },
  {
    id: "ct-clabsi-nicu",
    code: "CLABSI_NICU",
    name_ar: "القسطرة المركزية - NICU (CLABSI)",
    name_en: "Central Line-Associated Bloodstream Infection — NICU",
    active: true,
    sort_order: 6,
    departments: ["NICU"],
    items: [
      "1. Hand hygiene",
      "2. Maximal barrier precautions",
      "3. Cap",
      "4. Mask",
      "5. Sterile gloves",
      "6. Sterile gown",
      "7. Large sterile drape",
      "8. 2% chlorhexidine in alcohol for adults, pediatrics & neonates ≥2 months",
      "9. 2% aqueous chlorhexidine for neonates <2 weeks or <1500 g",
      "10. Subclavian vein for adults, femoral for pediatrics, and appropriate site for neonates",
      "11. Insertion compliance: compliant for the above (insertion bundle)",
      "12. Hand hygiene (maintenance)",
      "13. Daily assessment of catheter necessity with prompt removal",
      "14. Proper dressing choice (transparent semipermeable dressing)",
      "15. Proper frequency of dressing change",
      "16. Proper replacement of administration sets",
    ],
  },
];

function sampleAudit(overrides) {
  const items = overrides.items;
  const met = items.filter((i) => i.status === "MET").length;
  const notMet = items.filter((i) => i.status === "NOT MET").length;
  const applicable = met + notMet;
  return {
    id: crypto.randomUUID(),
    created_at: new Date().toISOString(),
    mrn: "",
    age: "",
    diagnosis: "",
    comments: "",
    action_status: notMet > 0 ? "open" : "none",
    deleted: false,
    met_count: met,
    not_met_count: notMet,
    applicable_count: applicable,
    compliance_pct: applicable > 0 ? Math.round((met / applicable) * 1000) / 10 : null,
    ...overrides,
  };
}

const today = new Date().toISOString().slice(0, 10);

export const ward_round_audits = [
  sampleAudit({
    date: today,
    department: "ICU",
    checklist_code: "CLABSI_ICU",
    checklist_name_ar: "القسطرة المركزية - ICU (CLABSI)",
    checklist_type_id: "ct-clabsi-icu",
    patient_name: "مريض تجريبي 1",
    mrn: "RH-1001",
    age: "54",
    diagnosis: "Sepsis",
    done_by: "ic",
    items: checklist_types[4].items.map((item, i) => ({ item, status: i === 12 ? "NOT MET" : "MET" })),
    comments: "تأخر تقييم الحاجة اليومية للقسطرة",
  }),
  sampleAudit({
    date: today,
    department: "NICU",
    checklist_code: "VAE_NICU",
    checklist_name_ar: "أجهزة التنفس - NICU (VAE)",
    checklist_type_id: "ct-vae-nicu",
    patient_name: "مريض تجريبي 2",
    mrn: "RH-1002",
    age: "3 أيام",
    diagnosis: "RDS",
    done_by: "ward",
    items: checklist_types[3].items.map((item) => ({ item, status: "MET" })),
  }),
  sampleAudit({
    date: today,
    department: "الجراحة",
    checklist_code: "SSI",
    checklist_name_ar: "الجراحة (SSI)",
    checklist_type_id: "ct-ssi",
    patient_name: "مريض تجريبي 3",
    mrn: "RH-1003",
    age: "40",
    diagnosis: "Appendectomy",
    done_by: "ic2",
    items: checklist_types[0].items.map((item, i) => ({ item, status: i === 3 ? "NA" : "MET" })),
  }),
];

export const app_config = {
  id: 1,
  staff_username: "ward",
  staff_password: "ward123",
  ic_username: "ic",
  ic_password: "ic123",
  ic2_username: "ic2",
  ic2_password: "ic2123",
  owner_username: "owner",
  owner_password: "owner123",
  departments: DEPARTMENTS,
};
