// Same default rows as supabase_schema.sql, used to power preview mode.
const DEPARTMENTS = ["ICU", "NICU", "Surgery", "OB/GYN"];
const HH_DEPARTMENTS = [
  "ICU",
  "Medical Ward",
  "Surgical Ward",
  "Emergency",
  "Pediatric",
  "NICU",
  "OPD",
  "OT",
  "Labor & Delivery",
  "Dialysis",
  "Other",
];

export const checklist_types = [
  {
    id: "ct-ssi",
    code: "SSI",
    name_ar: "Surgical Site Infection (SSI)",
    name_en: "Surgical Site Infection",
    active: true,
    sort_order: 1,
    departments: ["Surgery", "OB/GYN"],
    items: [
      "1. Antibiotic(s) was (were) given within one (1) hour before incision",
      "2. Prophylactic antibiotic(s) is (are) consistent with our guidelines",
      "3. Discontinuation of prophylactic antibiotic(s) within 24 hours",
      "4. Appropriate hair removal — Was hair at the incisional site removed appropriately",
      "5. Maintenance of pre/postoperative glucose control — Serum glucose target met",
      "6. Maintenance of pre/postoperative normothermia (for applicable procedures)",
      "7. Use appropriate antiseptic solution",
    ],
  },
  {
    id: "ct-cauti",
    code: "CAUTI",
    name_ar: "Catheter-Associated UTI (CAUTI)",
    name_en: "Catheter-Associated UTI",
    active: true,
    sort_order: 2,
    departments: ["ICU", "Surgery", "OB/GYN"],
    items: [
      "1. Avoid unnecessary urinary catheters",
      "2. Insert using aseptic technique",
      "3. Hand hygiene before insertion of urinary catheter",
      "4. Use sterile equipment (gloves, drape, sponges, sterile solution)",
      "5. Use of smallest catheter size as possible",
      "6. Maintain catheters based on recommended guidelines",
      "7. Maintain a sterile, continuously closed drainage system",
      "8. Keep catheter properly secured to prevent movement",
      "9. Keep collection bag below the level of the bladder at all times",
      "10. Maintain unobstructed urine flow",
      "11. Empty collection bag regularly",
      "12. Routine hygiene (cleansing of the meatal surface)",
      "13. Collection of urine samples should follow aseptic technique",
      "14. Review urinary catheter necessity daily and remove promptly when no longer indicated",
    ],
  },
  {
    id: "ct-vae-icu",
    code: "VAE_ICU",
    name_ar: "Ventilator-Associated Event — ICU (VAE)",
    name_en: "Ventilator-Associated Event — ICU",
    active: true,
    sort_order: 3,
    departments: ["ICU"],
    items: [
      "1. Elevation of the head of the bed to between 30 and 45 degrees",
      "2. Daily sedative interruption & daily assessment of readiness to extubate",
      "3. Peptic ulcer disease (PUD) prophylaxis",
      "4. Deep venous thrombosis (DVT) prophylaxis (unless contraindicated)",
      "5. Daily oral care with appropriate antiseptic solution",
    ],
  },
  {
    id: "ct-vae-nicu",
    code: "VAE_NICU",
    name_ar: "Ventilator-Associated Event — NICU (VAE)",
    name_en: "Ventilator-Associated Event — NICU",
    active: true,
    sort_order: 4,
    departments: ["NICU"],
    items: [
      "1. Hand hygiene",
      "2. Semi-recumbent position",
      "3. Mouth rinse with an appropriate solution",
      "4. Appropriate ventilator circuit care",
      "5. Daily assessment of readiness to extubate",
    ],
  },
  {
    id: "ct-clabsi-icu",
    code: "CLABSI_ICU",
    name_ar: "Central Line-Associated Bloodstream Infection — ICU (CLABSI)",
    name_en: "Central Line-Associated Bloodstream Infection — ICU",
    active: true,
    sort_order: 5,
    departments: ["ICU"],
    items: [
      "1. Hand hygiene",
      "2. Maximal barrier precautions",
      "3. Cap",
      "4. Mask",
      "5. Sterile gloves",
      "6. Sterile gown",
      "7. Large sterile drape",
      "8. 2% chlorhexidine in alcohol for adults, pediatrics & neonates ≥2 months",
      "9. 2% aqueous chlorhexidine for neonates <2 weeks or <1500 g",
      "10. Subclavian vein for adults, femoral for pediatrics, and appropriate site for neonates",
      "11. Insertion compliance: compliant for the above (insertion bundle)",
      "12. Hand hygiene (maintenance)",
      "13. Daily assessment of catheter necessity with prompt removal",
      "14. Proper dressing choice (transparent semipermeable dressing)",
      "15. Proper frequency of dressing change",
      "16. Proper replacement of administration sets",
    ],
  },
  {
    id: "ct-clabsi-nicu",
    code: "CLABSI_NICU",
    name_ar: "Central Line-Associated Bloodstream Infection — NICU (CLABSI)",
    name_en: "Central Line-Associated Bloodstream Infection — NICU",
    active: true,
    sort_order: 6,
    departments: ["NICU"],
    items: [
      "1. Hand hygiene",
      "2. Maximal barrier precautions",
      "3. Cap",
      "4. Mask",
      "5. Sterile gloves",
      "6. Sterile gown",
      "7. Large sterile drape",
      "8. 2% chlorhexidine in alcohol for adults, pediatrics & neonates ≥2 months",
      "9. 2% aqueous chlorhexidine for neonates <2 weeks or <1500 g",
      "10. Subclavian vein for adults, femoral for pediatrics, and appropriate site for neonates",
      "11. Insertion compliance: compliant for the above (insertion bundle)",
      "12. Hand hygiene (maintenance)",
      "13. Daily assessment of catheter necessity with prompt removal",
      "14. Proper dressing choice (transparent semipermeable dressing)",
      "15. Proper frequency of dressing change",
      "16. Proper replacement of administration sets",
    ],
  },
];

function sampleAudit(overrides) {
  const items = overrides.items;
  const met = items.filter((i) => i.status === "MET").length;
  const notMet = items.filter((i) => i.status === "NOT MET").length;
  const applicable = met + notMet;
  return {
    id: crypto.randomUUID(),
    created_at: new Date().toISOString(),
    mrn: "",
    age: "",
    diagnosis: "",
    comments: "",
    action_status: notMet > 0 ? "open" : "none",
    deleted: false,
    met_count: met,
    not_met_count: notMet,
    applicable_count: applicable,
    compliance_pct: applicable > 0 ? Math.round((met / applicable) * 1000) / 10 : null,
    ...overrides,
  };
}

const today = new Date().toISOString().slice(0, 10);

export const ward_round_audits = [
  sampleAudit({
    date: today,
    department: "ICU",
    checklist_code: "CLABSI_ICU",
    checklist_name_ar: "Central Line-Associated Bloodstream Infection — ICU (CLABSI)",
    checklist_type_id: "ct-clabsi-icu",
    patient_name: "Sample Patient 1",
    mrn: "RH-1001",
    age: "54",
    diagnosis: "Sepsis",
    done_by: "ic",
    items: checklist_types[4].items.map((item, i) => ({ item, status: i === 12 ? "NOT MET" : "MET" })),
    comments: "Delayed daily assessment of catheter necessity",
  }),
  sampleAudit({
    date: today,
    department: "NICU",
    checklist_code: "VAE_NICU",
    checklist_name_ar: "Ventilator-Associated Event — NICU (VAE)",
    checklist_type_id: "ct-vae-nicu",
    patient_name: "Sample Patient 2",
    mrn: "RH-1002",
    age: "3 days",
    diagnosis: "RDS",
    done_by: "ward",
    items: checklist_types[3].items.map((item) => ({ item, status: "MET" })),
  }),
  sampleAudit({
    date: today,
    department: "Surgery",
    checklist_code: "SSI",
    checklist_name_ar: "Surgical Site Infection (SSI)",
    checklist_type_id: "ct-ssi",
    patient_name: "Sample Patient 3",
    mrn: "RH-1003",
    age: "40",
    diagnosis: "Appendectomy",
    done_by: "ic2",
    items: checklist_types[0].items.map((item, i) => ({ item, status: i === 3 ? "NA" : "MET" })),
  }),
];

const STOCK_DEPARTMENTS = [
  "Cath Lab",
  "OR Anesthesia",
  "OR Nursing",
  "DR",
  "ICU",
  "NICU",
  "FW",
  "MW",
  "Endoscopy",
  "IM 1 & 2",
  "Cardiology",
  "Pulmo",
  "ENT 1 & 2",
  "Dental 1 & 2",
  "Ophthalmology",
  "Neurology",
  "Pedia OPD",
  "Derma",
  "OB & GYN",
  "Ortho",
  "Urology & ESWL",
  "Surgery",
  "Emergency Room",
];

const EMPLOYEE_DEPARTMENTS = [
  "Nursing",
  "Physicians",
  "Laboratory",
  "Radiology",
  "Housekeeping",
  "Dietary",
  "Pharmacy",
  "Administration",
  "Maintenance",
  "Other",
];

export const app_config = {
  id: 1,
  departments: DEPARTMENTS,
  hh_departments: HH_DEPARTMENTS,
  hh_observer_roles: ["Doctor", "Nurse", "Housekeeping", "Lab Staff", "Radiology"],
  hh_department_observers: {},
  stock_departments: STOCK_DEPARTMENTS,
  employee_departments: EMPLOYEE_DEPARTMENTS,
};

export const hh_observations = [
  {
    id: "hh-1",
    date: today,
    department: "ICU",
    observer: "Nurse",
    time_from: "09:00",
    time_to: "09:15",
    before_touching_patient: 1,
    before_clean_procedure: 1,
    after_body_fluid_risk: 1,
    after_touching_patient: 0,
    after_touching_surroundings: 1,
    wearing_glove: 1,
    missed: null,
    hand_wash: 1,
    hand_rub: 0,
    total_opportunities: 6,
    compliant: 5,
    compliance_pct: 83.3,
    done_by: "ic",
    deleted: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "hh-2",
    date: today,
    department: "NICU",
    observer: "Doctor",
    time_from: "10:30",
    time_to: "10:42",
    before_touching_patient: 1,
    before_clean_procedure: 1,
    after_body_fluid_risk: null,
    after_touching_patient: 1,
    after_touching_surroundings: 1,
    wearing_glove: 1,
    missed: null,
    hand_wash: 0,
    hand_rub: 1,
    total_opportunities: 5,
    compliant: 5,
    compliance_pct: 100,
    done_by: "ic",
    deleted: false,
    created_at: new Date().toISOString(),
  },
];

export const stock_items = [
  { id: "item-1", department: "ICU", name: "SHARP CONTAINER", unit: "unit", min_qty: 5, max_qty: 10, current_qty: 0, active: true, sort_order: 1 },
  { id: "item-2", department: "Emergency Room", name: "NORMAL SALINE 500ML", unit: "unit", min_qty: 20, max_qty: 30, current_qty: 30, active: true, sort_order: 2 },
  { id: "item-3", department: "OR Nursing", name: "SURGICAL GOWN", unit: "unit", min_qty: 100, max_qty: 200, current_qty: 172, active: true, sort_order: 3 },
];

export const stock_requests = [
  {
    id: "req-1",
    date: today,
    department: "Emergency Room",
    item_id: "item-2",
    item_name: "NORMAL SALINE 500ML",
    unit: "unit",
    quantity_requested: 3,
    quantity_issued: 3,
    status: "issued",
    notes: "",
    requested_by: "ward",
    issued_by: "ward",
    issued_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
];

export const health_item_types = [
  { id: "hit-1", name: "Hepatitis B (series)", category: "vaccine", recurrence_months: null, dose_schedule: [0, 1, 6], kitchen_only: false, active: true, sort_order: 1 },
  { id: "hit-2", name: "MMR (Measles, Mumps, Rubella)", category: "vaccine", recurrence_months: null, dose_schedule: [0, 1], kitchen_only: false, active: true, sort_order: 2 },
  { id: "hit-3", name: "Varicella (Chickenpox)", category: "vaccine", recurrence_months: null, dose_schedule: [0, 1], kitchen_only: false, active: true, sort_order: 3 },
  { id: "hit-4", name: "Influenza (Annual)", category: "vaccine", recurrence_months: 12, dose_schedule: [0], kitchen_only: false, active: true, sort_order: 4 },
  { id: "hit-5", name: "Tetanus toxoid", category: "vaccine", recurrence_months: null, dose_schedule: [0], kitchen_only: false, active: true, sort_order: 5 },
  { id: "hit-6", name: "Meningococcal (Kitchen Staff)", category: "vaccine", recurrence_months: null, dose_schedule: [0], kitchen_only: true, active: true, sort_order: 6 },
  { id: "hit-7", name: "Typhoid (Kitchen Staff)", category: "vaccine", recurrence_months: null, dose_schedule: [0], kitchen_only: true, active: true, sort_order: 7 },
  { id: "hit-8", name: "Hepatitis A (Kitchen Staff)", category: "vaccine", recurrence_months: null, dose_schedule: [0, 1, 6], kitchen_only: true, active: true, sort_order: 8 },
];

export const employees = [
  {
    id: "emp-1",
    employee_no: "E-1001",
    name: "Amal Al-Harbi",
    department: "Nursing",
    job_title: "Staff Nurse",
    file_no: "F-201",
    iqama_no: "2xxxxxxxx1",
    date_of_birth: "1990-04-12",
    phone: "05xxxxxxx1",
    is_kitchen_staff: false,
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "emp-2",
    employee_no: "E-1002",
    name: "Yousef Al-Qahtani",
    department: "Dietary",
    job_title: "Cook",
    file_no: "F-202",
    iqama_no: "2xxxxxxxx2",
    date_of_birth: "1988-09-03",
    phone: "05xxxxxxx2",
    is_kitchen_staff: true,
    active: true,
    created_at: new Date().toISOString(),
  },
];

export const employee_health_records = [
  {
    id: "ehr-1",
    employee_id: "emp-1",
    item_type_id: "hit-4",
    item_name: "Influenza (Annual)",
    dose_number: 1,
    batch_no: "INF-0026",
    date_given: today,
    result: "",
    next_due_date: null,
    notes: "",
    recorded_by: "ic",
    created_at: new Date().toISOString(),
  },
];

export const employee_vaccine_requests = [
  { id: "evr-1", employee_id: "emp-1", item_type_id: "hit-4", requested_at: new Date().toISOString(), requested_by: "ic" },
];

export const employee_clinic_status = [
  {
    id: "ecs-1",
    employee_id: "emp-1",
    investigation_status: "review_done",
    ppd_status: "done",
    ppd_test_date: today,
    ppd_next_due_date: null,
    stool_urine_status: null,
    stool_urine_test_date: null,
    stool_urine_next_due_date: null,
    icn_remarks: "",
    updated_by: "ic",
    updated_at: new Date().toISOString(),
  },
];

export const disease_types = [
  { id: "dt-1", name: "Tuberculosis (TB)", active: true, sort_order: 1 },
  { id: "dt-2", name: "Measles", active: true, sort_order: 2 },
  { id: "dt-3", name: "COVID-19", active: true, sort_order: 4 },
  { id: "dt-99", name: "Other", active: true, sort_order: 99 },
];

export const communicable_cases = [
  {
    id: "case-1",
    date: today,
    patient_name: "Sample Patient",
    rh_no: "RH-2001",
    status: "suspected",
    disease_type_id: "dt-1",
    disease_name: "Tuberculosis (TB)",
    disease_other: "",
    reported_at: null,
    attachment1_path: null,
    attachment1_name: null,
    attachment2_path: null,
    attachment2_name: null,
    attachment2_not_required: false,
    ipc_note: "",
    done_by: "ic",
    deleted: false,
    created_at: new Date().toISOString(),
  },
];

export const users = [
  {
    id: "user-owner",
    username: "owner",
    password: "owner123",
    display_name: "Owner",
    role: "owner",
    department: null,
    active: true,
    must_change_password: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "user-ic",
    username: "ic",
    password: "ic123",
    display_name: "Infection Control",
    role: "ic",
    department: null,
    active: true,
    must_change_password: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "user-ward",
    username: "ward",
    password: "ward123",
    display_name: "Ward Staff",
    role: "staff",
    department: "ICU",
    active: true,
    must_change_password: false,
    created_at: new Date().toISOString(),
  },
];
